stages:
   - deploy

production:
   stage: deploy
   script:
      - curl.exe -k -X GET https://api.sakku.cloud/ci/app/2203/rebuild/token/a0738495-ff60-48db-98fd-d7f9440ddba8
   only:
      - master
   tags:
      - apptest
